/*
 * This file is generated by jOOQ.
 */
package de.tobchen.health.patientindex.main.jooq.public_;


import de.tobchen.health.patientindex.main.jooq.public_.tables.Patients;
import de.tobchen.health.patientindex.main.jooq.public_.tables.records.PatientsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PatientsRecord> PATIENTS_PKEY = Internal.createUniqueKey(Patients.PATIENTS, DSL.name("patients_pkey"), new TableField[] { Patients.PATIENTS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PatientsRecord, PatientsRecord> PATIENTS__PATIENTS_MERGED_INTO_FKEY = Internal.createForeignKey(Patients.PATIENTS, DSL.name("patients_merged_into_fkey"), new TableField[] { Patients.PATIENTS.MERGED_INTO }, Keys.PATIENTS_PKEY, new TableField[] { Patients.PATIENTS.ID }, true);
}
