/*
 * This file is generated by jOOQ.
 */
package de.tobchen.health.patientindex.main.jooq.public_;


import de.tobchen.health.patientindex.main.jooq.public_.tables.Patient;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.patient</code>.
     */
    public static final Patient PATIENT = Patient.PATIENT;
}
