services:
  jaeger:
    image: jaegertracing/all-in-one:1.54.0
    ports:
      - 127.0.0.1:16686:16686
  prometheus:
    image: prom/prometheus:v2.49.1
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./compose-settings/prometheus.yaml:/etc/prometheus/prometheus.yml

  postgres-patient-index-main:
    image: postgres:16.1-bullseye
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  postgres-patient-index-feed:
    image: postgres:16.1-bullseye
    ports:
      - 127.0.0.1:5442:5432
    environment:
      - POSTGRES_PASSWORD=password
  
  patient-index-feed-consumer:
    build: ./patient-index-feed-consumer

  patient-index-main:
    build: ./patient-index-main
    ports:
      - 127.0.0.1:8080:8080
    env_file:
      - path: ./compose-settings/default.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-patient-index-main:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./otel:/otel
  
  patient-index-feed:
    build: ./patient-index-feed
    env_file:
      - path: ./compose-settings/default.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-patient-index-feed:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./otel:/otel
  
  patient-index-ws:
    build: ./patient-index-ws
    ports:
      - 127.0.0.1:9080:8080
    env_file:
      - path: ./compose-settings/default.env
    volumes:
      - ./otel:/otel

