services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 127.0.0.1:16686:16686
      - 127.0.0.1:4317:4317
  patient-index:
    build: ./patient-index
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - JAVA_TOOL_OPTIONS="-javaagent:/otel/opentelemetry-javaagent.jar"
      - OTEL_SERVICE_NAME=patient-index
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4317
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    volumes:
      - ./otel:/otel
    network_mode: host

