services:
  test-jaeger:
    image: jaegertracing/all-in-one:1.54.0
    ports:
      - 127.0.0.1:4317:4317
      - 127.0.0.1:4318:4318
      - 127.0.0.1:16686:16686
  test-prometheus:
    image: prom/prometheus:v2.49.1
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prom/prometheus.yaml:/etc/prometheus/prometheus.yml
  test-postgres-patient-index:
    image: postgres:16.1-bullseye
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  test-postgres-patient-index-feed:
    image: postgres:16.1-bullseye
    ports:
      - 127.0.0.1:5442:5432
    environment:
      - POSTGRES_PASSWORD=password
  test-patient-index-feed-consumer:
    build: ./patient-index-feed-consumer
    ports:
      - 127.0.0.1:6060:6060
