services:
  jaeger:
    image: jaegertracing/all-in-one:1.54.0
    ports:
      - 127.0.0.1:4317:4317
      - 127.0.0.1:4318:4318
      - 127.0.0.1:16686:16686
  postgres-patient-index:
    image: postgres:16.1-bullseye
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=password
