/*
 * This file is generated by jOOQ.
 */
package de.tobchen.health.patientindex.feed.jooq.public_;


import de.tobchen.health.patientindex.feed.jooq.public_.tables.IdValue;
import de.tobchen.health.patientindex.feed.jooq.public_.tables.Message;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.id_value</code>.
     */
    public static final IdValue ID_VALUE = IdValue.ID_VALUE;

    /**
     * The table <code>public.message</code>.
     */
    public static final Message MESSAGE = Message.MESSAGE;
}
