/*
 * This file is generated by jOOQ.
 */
package de.tobchen.health.patientindex.main.jooq.public_.tables.records;


import de.tobchen.health.patientindex.main.jooq.public_.tables.Patient;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PatientRecord extends UpdatableRecordImpl<PatientRecord> implements Record5<String, Integer, OffsetDateTime, JSONB, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.patient.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.patient.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.patient.version_id</code>.
     */
    public void setVersionId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.patient.version_id</code>.
     */
    public Integer getVersionId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.patient.last_updated</code>.
     */
    public void setLastUpdated(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.patient.last_updated</code>.
     */
    public OffsetDateTime getLastUpdated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.patient.identifiers</code>.
     */
    public void setIdentifiers(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.patient.identifiers</code>.
     */
    public JSONB getIdentifiers() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.patient.merged_into</code>.
     */
    public void setMergedInto(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.patient.merged_into</code>.
     */
    public String getMergedInto() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, Integer, OffsetDateTime, JSONB, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, Integer, OffsetDateTime, JSONB, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Patient.PATIENT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Patient.PATIENT.VERSION_ID;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return Patient.PATIENT.LAST_UPDATED;
    }

    @Override
    public Field<JSONB> field4() {
        return Patient.PATIENT.IDENTIFIERS;
    }

    @Override
    public Field<String> field5() {
        return Patient.PATIENT.MERGED_INTO;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getVersionId();
    }

    @Override
    public OffsetDateTime component3() {
        return getLastUpdated();
    }

    @Override
    public JSONB component4() {
        return getIdentifiers();
    }

    @Override
    public String component5() {
        return getMergedInto();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getVersionId();
    }

    @Override
    public OffsetDateTime value3() {
        return getLastUpdated();
    }

    @Override
    public JSONB value4() {
        return getIdentifiers();
    }

    @Override
    public String value5() {
        return getMergedInto();
    }

    @Override
    public PatientRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public PatientRecord value2(Integer value) {
        setVersionId(value);
        return this;
    }

    @Override
    public PatientRecord value3(OffsetDateTime value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    public PatientRecord value4(JSONB value) {
        setIdentifiers(value);
        return this;
    }

    @Override
    public PatientRecord value5(String value) {
        setMergedInto(value);
        return this;
    }

    @Override
    public PatientRecord values(String value1, Integer value2, OffsetDateTime value3, JSONB value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientRecord
     */
    public PatientRecord() {
        super(Patient.PATIENT);
    }

    /**
     * Create a detached, initialised PatientRecord
     */
    public PatientRecord(String id, Integer versionId, OffsetDateTime lastUpdated, JSONB identifiers, String mergedInto) {
        super(Patient.PATIENT);

        setId(id);
        setVersionId(versionId);
        setLastUpdated(lastUpdated);
        setIdentifiers(identifiers);
        setMergedInto(mergedInto);
        resetChangedOnNotNull();
    }
}
