/*
 * This file is generated by jOOQ.
 */
package de.tobchen.health.patientindex.main.jooq.public_.tables.records;


import de.tobchen.health.patientindex.main.jooq.public_.tables.Patients;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PatientsRecord extends UpdatableRecordImpl<PatientsRecord> implements Record4<String, OffsetDateTime, JSONB, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.patients.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.patients.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.patients.last_updated</code>.
     */
    public void setLastUpdated(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.patients.last_updated</code>.
     */
    public OffsetDateTime getLastUpdated() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.patients.identifiers</code>.
     */
    public void setIdentifiers(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.patients.identifiers</code>.
     */
    public JSONB getIdentifiers() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.patients.merged_into</code>.
     */
    public void setMergedInto(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.patients.merged_into</code>.
     */
    public String getMergedInto() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, OffsetDateTime, JSONB, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, OffsetDateTime, JSONB, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Patients.PATIENTS.ID;
    }

    @Override
    public Field<OffsetDateTime> field2() {
        return Patients.PATIENTS.LAST_UPDATED;
    }

    @Override
    public Field<JSONB> field3() {
        return Patients.PATIENTS.IDENTIFIERS;
    }

    @Override
    public Field<String> field4() {
        return Patients.PATIENTS.MERGED_INTO;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public OffsetDateTime component2() {
        return getLastUpdated();
    }

    @Override
    public JSONB component3() {
        return getIdentifiers();
    }

    @Override
    public String component4() {
        return getMergedInto();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public OffsetDateTime value2() {
        return getLastUpdated();
    }

    @Override
    public JSONB value3() {
        return getIdentifiers();
    }

    @Override
    public String value4() {
        return getMergedInto();
    }

    @Override
    public PatientsRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public PatientsRecord value2(OffsetDateTime value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    public PatientsRecord value3(JSONB value) {
        setIdentifiers(value);
        return this;
    }

    @Override
    public PatientsRecord value4(String value) {
        setMergedInto(value);
        return this;
    }

    @Override
    public PatientsRecord values(String value1, OffsetDateTime value2, JSONB value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientsRecord
     */
    public PatientsRecord() {
        super(Patients.PATIENTS);
    }

    /**
     * Create a detached, initialised PatientsRecord
     */
    public PatientsRecord(String id, OffsetDateTime lastUpdated, JSONB identifiers, String mergedInto) {
        super(Patients.PATIENTS);

        setId(id);
        setLastUpdated(lastUpdated);
        setIdentifiers(identifiers);
        setMergedInto(mergedInto);
        resetChangedOnNotNull();
    }
}
