logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: trace
      springframework.transaction.interceptor.TransactionInterceptor: trace
    de.tobchen: trace

patient-index:
  fhir:
    server: http://localhost:8080/fhir/r5
