logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: trace
      springframework.transaction.interceptor.TransactionInterceptor: trace
    de.tobchen: trace

server.port: 8080